### ISSUE TITLE
Documentation for the Sky programming model

### ISSUE THREAD

**Issue by mishadynin** [flutter/engine#1151]
Better docs would help develop a better mental model of how Sky works for new developers adopting it.  Some questions that came up for me:

* What's the lifecycle of a Widget?  When is it Ok to call which methods?
* It seems that you can only create new Widgets from build() methods.  What are other restrictions that generate a runtime error but aren't enforced by static checks?
* When can the developer use existing Widgets, and when do you have to subclass Component and StatefulComponent?
* What is a contract on the Component implementation?  What should I do and what can't I do?  What's the deal with syncConstructorArguments()?
* How is Sky model different from Swing and GWT frameworks?

**Comment by abarth** [comment]
/cc @Hixie 

I'll take a pass at a first draft of this doc.

**Comment by abarth** [comment]
Some of these topics are addressed at the end of the tutorial <https://flutter.github.io/tutorial/>, but we should present the information in reference form.

**Comment by abarth** [comment]
> What's the lifecycle of a Widget?

Sorry it took so long to answer your question.  When I drew out the diagram for the lifecycle of a widget, it didn't many any sense, so we did a big refactoring project to fix it.  Now the state machines make sense and are draw in this slide deck:

https://docs.google.com/presentation/d/1cw7A4HbvM_Abv320rVgPVGiUP2msVs7tfGbkgdrTy0I/edit?usp=sharing

> When is it Ok to call which methods?

This is now documented in dartdoc for each method.

> It seems that you can only create new Widgets from build() methods.

This is no longer the case.  Now you can create widget whenever you like.

> What are other restrictions that generate a runtime error but aren't enforced by static checks?

There are lots of them.  We use asserts liberally throughout the codebase to enforce various path-dependent invariants of the system.  For example, `initState` needs to call `super.initState` or it will trigger an assert.  Hopefully these asserts have reasonable messages that explain the issue.  If you run into some that are mysterious, please file bugs and we'll attempt to demystify them.

> When can the developer use existing Widgets, and when do you have to subclass Component and StatefulComponent?

Widgets are meant to be used by composition rather than subclassing.  That means you almost always subclass StatelessComponent or StatefulComponent and return tree of Widgets in your build function.  There are still a few cases where we subclass widgets (e.g., `Scrollable`), but we've been using less of that over time.

It's very possible that we shouldn't be using subclassing in `Scrollable` either.  We might want to look at that issue at some point.

> What is a contract on the Component implementation? What should I do and what can't I do?

This should now be documented in dartdoc comments.  If the dartdoc comments are insufficient, please file a bug with specifics and we'll improve them.

> What's the deal with syncConstructorArguments()?

We've removed syncConstructorArguments from the system because it was too confusing.

> How is Sky model different from Swing and GWT frameworks?

The main difference is that Flutter is a functional-reactive system, which means the "create" and "update" steps in Swing and GWT are combined into a single "build" step.  The other major difference is that you build Flutter widgets by composition rather than inheritance.  I'm not sure how best to document these ideas other than to say them in the getting started guide and in the tutorial.  If you have specific ideas for how we can improve the docs in connection with this question, would you be willing to talk with me in person?  That's probably a better way to get something useful here than creating a long bug thread.

Thanks for filing this issue.  Working through your questions motivated me to make a lot of improvements to the system (e.g., drawing out the component lifecycle made me very interested in doing fn3).
