### ISSUE TITLE
Checkbox colour transition has a step

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1374]
Scale up a checkbox with the scheduler's scale set to 10.0 or some such, and tap a checkbox. It transitions its colour, but at the very last second, it snaps it to a new colour instead of ending on the colour it transitioned to.

**Comment by mdakin** [comment]
Hi, I could have a look at this, I created an example application with a big checkbox, but I did not understand the bit about scheduler bit. Did you mean to slow down the checkbox animation to see the colour transition?

**Comment by mdakin** [comment]
Probably you meant using timeDilation to slow it down.  I set it to 20.0 but in slo-mo color transition look fine on my Nexus-5.

**Comment by Hixie** [comment]
yeah, I meant timeDilation.

You may have to change the default theme to see this.

**Comment by mdakin** [comment]
I changed the theme, blue background and red accent. I am not sure I see the issue you described, I made the checkbox huge, slowed down animation 20 times, doubled stroke width and took some screen captures for dark and light themes:

dark: https://goo.gl/photos/9S9mwsPsdW3r4mwG7 
light: https://goo.gl/photos/dbggnaoyuCnsmtyZA

I can see other minor issues like: 
- Artefacts right before checkmark's disappearance.
- Inner and outer rectangles color differences.
- Is radial gradient in the middle intentional?

**Comment by Hixie** [comment]
Odd, that wasn't what I saw at all. I'll have to study it again.

**Comment by mdakin** [comment]
Sure. I can fix other issues though. Is there a canonical material design checkbox reference implementation (with animations etc.) I could follow? I only see descriptions in material design website.

**Comment by Hixie** [comment]
I think we just try to follow what the spec says.

**Comment by mdakin** [comment]
https://github.com/flutter/engine/pull/1513 might have fixed this issue.
Btw, I could not find a spec defining animations for individual widgets, but tried to follow existing visuals.

**Comment by abarth** [comment]
Seems to be fixed in #1513
