### ISSUE TITLE
Grid's maxChildExtent vs nChildrenPerRow

### ISSUE THREAD

**Issue by afandria** [flutter/engine#1464]
What is `maxChildExtent` in the `Grid` widget?

When building a Color Picker and Image Picker it turned out that the Grid was an excellent choice of Widget. `maxChildExtent` is a required "optional" parameter, but I'm not sure what it does. It seems like the value could be some sort of percent scaling of the children.

When it was 100.0, I could fit 3 of my Network Images on the same line. 75.0 let me fit 4 on the same line. I'm not really sure what's going on, but it's interesting.

However, I would prefer "fit X children on the same line" (`nChildrenPerRow`) as a more valuable number than `maxChildExtent`, since that will scale better for children of different sizes and for devices of different sizes.

**Comment by abarth** [comment]
The grid makes the children as big as they can be while still fitting in the given size and while being at most max child extent.

We could have numberOfChildrenPerRow, but if you designed your app in landscape and then switched to portrait, you'd end up with the same number of children in a row but they would be much larger because they'd have to stretch to fill a much larger screen.  The idea with maxChildExtent is that you have some idea how big you want the children to be and you'd like to fit as many as you can on the screen.

Put another way, if you knew how many children you wanted per line, you could just use a Row with that many Flexible children.

**Comment by afandria** [comment]
That's a good point about Row and landscape.

However, I still don't know what `maxChildExtent` means. Is that the number of Flutter pixels?
Looking at it again, perhaps my Dialog size only allows around 300.0 Flutter pixels.

**Comment by abarth** [comment]
Yeah, it's in logical pixels.

**Comment by afandria** [comment]
Thanks!
