### ISSUE TITLE
Transitions cause scroll position of ScrollableBlock to be lost.

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#602]

**Comment by abarth** [comment]
/cc @mpcomplete @Hixie 

We probably need to make the sync algorithm smarter to be able to sync children with grandchildren.

**Comment by mpcomplete** [comment]
How can I reproduce this?

**Comment by abarth** [comment]
Create a ScrollableBlock and fill it with a randbow of Contains.  Scroll down a ways.  Then when you tap a button, add a FadeTransition that wraps the ScrollableBlock.  The scroll position will reset to the top.

It's not really a problem with transitions.  The problem is that the sync algorithm in the underying widget framework isn't smart enough to realize that you inserted something into the tree and so the scrollable block gets recreated from scratch and we lose its scroll offset.

**Comment by abarth** [comment]
@apwilson This should now be fixed if you give some widget between your transition and your scrollable a global key.  For example, you can give the scrollable a global key.

**Comment by abarth** [comment]
I'm going to mark this as fixed based on the comment above.  Please re-open if this is still an issue.
