### ISSUE TITLE
Is there a roadmap?

### ISSUE THREAD

**Issue by thinkwing** [flutter/engine#637]
Hi,
Is there a roadmap?

**Comment by eseidel** [comment]
We currently have no public roadmap, no.  We're meeting to to our next round of planning this week and can probably share some of that.  Right now we're very focused on getting Sky on iOS to work as well as the Android version (a large part of that is blocked by currently running the Dart ARM Simulator on iOS due to inability to JIT code on iOS, the Dart VM team is working on App-Store compatible solutions for that issue as we speak).  We're also looking around both (mostly) internally and externally for early-adopter partners who are interested in working with us closely to develop their next mobile app on top of Sky.

I hope that helps. We're also available on #sky on freenode as well as sky-dev@googlegroups.com to discuss more.

**Comment by abarth** [comment]
I don't think we're going to share a roadmap publicly.
