### ISSUE TITLE
SnackBars show behind the keyboard

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/engine#810]
Not sure if they're supposed to sit above the keyboard or what?  Or maybe we're supposed to use a different widget when the keyboard is visible?

I discovered this by entering an invalid number in the fitness app.

**Comment by j9brown** [comment]
FWIW, Android won't tell you whether the keyboard is visible.

So in general the application is left with deciding how it wants to deal
with incursions into its space by an IME or other parts of the system UI
based on other information provided during layout, particularly the content
insets.

The Android window manager provides the application with content inserts
which represent what part of the window will be visible.  The app may be
able to draw outside of that region but what it draws there may or may not
be visible since it might be covered by decorations like the status bar but
that's how translucent decorations work.  Typically the app will adjust its
content view's layout to fit that region (the framework can do this
automatically).

If you've got a snack bar, you'll want to anchor it to the bottom of the
content region of the window.

It may help to think of the app's layout as having both an outer decor part
(which contains the background and decor elements like the title bar which
fill the window) and an inner content part (which fits within the decor and
adjusts as the content region changes).

NB. I might be getting the details slightly wrong.  There are also
affordances for things like overscan regions but I think most of that is
hidden from the API.

See also:
https://developer.android.com/reference/android/view/View.html#setFitsSystemWindows(boolean)
