### ISSUE TITLE
sky/examples/game has 150ms Dart GC pauses

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#84]
_From @eseidelGoogle on June 4, 2015 22:41_

sky/examples/game has 150ms Dart GC pauses

Not sure if this is Dart's problem our Sky's problem or this example's problem or all of the above.  But the game noticeably janks every couple seconds as we drop 10 frames for a GC.

@iposva-google @vlidholt 

_Copied from original issue: domokit/mojo#202_

**Comment by Hixie** [comment]
_From @eseidelGoogle on June 4, 2015 22:42_

Here is an example trace with a single GC pause:
http://filebin.ca/247fiWDumeEI/sky-trace-2015-06-04-223906.json

**Comment by Hixie** [comment]
_From @sethladd on June 4, 2015 22:55_

cc @kodandersson

**Comment by Hixie** [comment]
_From @eseidelGoogle on June 5, 2015 0:1_

sky/tools/shelldb start out/androidRelease sky/examples/game/main.dart
sky/tools/shelldb start_tracing
sky/tools/shelldb stop_tracing

Then open the resulting trace file in about:tracing in chrome.

**Comment by Hixie** [comment]
_From @kodandersson on June 5, 2015 5:48_

I'm having some trouble producing a recent build of sky ("Failed to download Go tool binaries"), but I will try to reproduce this again tomorrow.

The stderr log output produced by adding the flag --verbose_gc to your dart invocation would be useful to diagnose this.

**Comment by Hixie** [comment]
_From @eseidelGoogle on June 10, 2015 17:7_

I'm no longer seeing the 150ms GC pauses on tip of tree.  I believe because @vlidholt removed Box2d from the demo.  Here is a GC log of tip of tree:
https://gist.github.com/eseidelGoogle/6f34ad00d1f906a4245c

**Comment by Hixie** [comment]
_From @eseidelGoogle on June 10, 2015 17:14_

I lied.  The GCs are still here.  Here is a trace showing a 140ms GC of the tip of tree game/main.dart.
http://filebin.ca/24mB9pMvoTAK/sky-trace-2015-06-10-171241.json

**Comment by Hixie** [comment]
_From @eseidelGoogle on June 10, 2015 17:16_

Here is the patch I used to add --verbose_gc in case you'd like to do so locally:
https://gist.github.com/eseidelGoogle/7c1185d642acf8c14cad

**Comment by Hixie** [comment]
_From @eseidelGoogle on June 22, 2015 21:26_

@kodandersson is this a bug you'd like to track separately from the planned GC re-write?  iirc you (or maybe @iposva-google) mentioned to me before vacation that the verbose log seemed large/odd.

This issue will block production Sky apps, but *definitely* does not block Sky development at current.

**Comment by Hixie** [comment]
_From @kodandersson on June 23, 2015 1:2_

This should be tracked as a separate issue. The GC log shows ~150 ms pauses for collecting a 16 MB young generation, which is quite excessive. The timing breakdown shows most of that is spent processing weak references. I will try to get a detailed CPU profile.

How does Sky use weak references currently?

**Comment by Hixie** [comment]
_From @iposva-google on June 23, 2015 1:6_

Daniel, thanks for identifying the surprisingly large number of weak references. Let's use this issue to track down the source of weak references. It would be interesting to see where these originate.

The general on-going GC rewrite does not need to be tracked in this issue.

**Comment by Hixie** [comment]
_From @eseidelGoogle on June 23, 2015 1:52_

I presume "weak references" means usage of Dart_WeakPersistentHandle?  In which case we use them for several things in Sky, including the WTF String cache, as well as some logic for closing mojo handles, etc:

https://github.com/domokit/mojo/search?utf8=%E2%9C%93&q=Dart_WeakPersistentHandle

This is probably a good question for @abarth (who wrote much of this code).

**Comment by Hixie** [comment]
_From @abarth on June 23, 2015 2:6_

I would imagine the main source of weak persistent handles is that we use them to associate C++ state with Dart objects so that we can clean up the C++ state when the Dart object is no longer needed.

**Comment by zanderso** [comment]
I was able to reproduce using these instructions. When I made the finalizer for the weak handles a no-op---that is making DartWrappable::FinalizeDartWrapper do nothing---the long delays no longer happened. This indicates that the delay is due to the work being done by the finalizer calls rather than the bookkeeping and looping over handles in the VM.

As for what to do about the delays, I'm not sure the VM is the right place to try to, e.g. call the finalizers in smaller batches, or do some other trick so that they don't pile up and cause one big delay. Maybe that would be something to try on the Sky side, where the finalizer could just make a list of the work to do bit-by-bit sometime later, instead of all-at-once during Dart GC.

Alternately, what we do with Mojo handles in the Dart bindings is have an explicit close() call in Dart, and use the finalizer for the associated weak handle only for checking that close() has been called. (And even that we could disable in Release mode if it was a performance problem). Not sure how cumbersome that would be for Sky though.

**Comment by kodandersson** [comment]
The long pauses occur, somewhat surprisingly to me, during young generation collection. @Hixie  Is it expected that these objects are numerous and short-lived? Also, since @zanderso told me most finalizers are just "delete", are you using a C++ allocator with thread-local allocation, or is there locking involved in freeing the memory, or other potentially blocking operations in destructors?

Exactly how and when to run the finalizers in our upcoming concurrent GC is still not set in stone. For instance, should the finalizers be required to be thread-safe on the embedder's side? Understanding this particular case in more detail might help inform some of these decisions.

**Comment by abarth** [comment]
It sounds like the next step here is to try to do better on the Sky side.  For example, we could start by logging the types of objects that are being finalized to see if they're predominately of a specific type (e.g., Paint objects).  If that's the case, we can potentially be more clever in how we manage the memory for that specific type (e.g., maybe even avoiding needing finalizers at all).

**Comment by kodandersson** [comment]
I agree, understanding the population and lifetime better would be great (regardless of which parts/side need to "do better"). Thanks!

**Comment by abarth** [comment]
If you have a setup to reproduce this, can you dump a list for the runtimeType.toString() of the objects being finalized?  I'd be curious to see what types we're talking about.

**Comment by zanderso** [comment]
I took the interface_name strings from the DartWrapperInfo records:

https://gist.github.com/zanderso/7a6ba3c6450fcd011ecd

**Comment by abarth** [comment]
Looks like Paint and ColorFilters mostly.  I bet we can make those normal Dart object without finalizers.

**Comment by Hixie** [comment]
We could cache those even more aggressively. Currently, yes, they are expected to be created and discarded very frequently (many times per frame).

I guess we could make them just store instructions for what to create on the C++ side, but then we'd be creating SkPaints a whole lot instead. I dunno how cheap that is.

cc @mpcomplete

**Comment by abarth** [comment]
I bet the game doesn't cache them.

**Comment by eseidelGoogle** [comment]
The game currently allocates ColorFilters per particle per frame. :)  I'm sure there are lots of other examples of allocating a zillion weak handles:
https://github.com/domokit/sky_engine/blob/master/sky/sdk/example/game/lib/particle_system.dart#L302

**Comment by Hixie** [comment]
cc @mtklein

**Comment by mtklein** [comment]
Here's what I know performance-wise about SkPaint.

SkPaint's layout is currently 10 pointers and 7 32-bit fields, which I think sums to 68 or 112 bytes depending on your pointer size.

Each of those 10 pointers is a potential effect, like a typeface, shader, transfer mode, or color filter.  Paint effects are all immutable and reference-counted, so SkPaint::setFoo(Foo*) calls Foo::ref(), and ~SkPaint() calls unref() on any non-NULL effects.  This ref-counting is atomic, and generally unref() is more expensive than ref(), both due to the fact that unref() needs to call delete when the count hits zero, and to the stronger memory barriers required (particularly more expensive on ARM than x86).  This ref-counting dwarfs anything else in the destructor like null checks, so the cost of ~SkPaint() basically scales linearly with the number of non-null effects attached, with a small constant cost.

One of the larger consumers of time and memory while recording an SkPicture is recording the SkPaints from the various drawFoo(Foo, SkPaint) calls.  The fastest approach we've found so far for recording SkPaints is to simply copy them by value (i.e. byte copy the struct, ref() all non-null effects) directly into the picture.  So each paint going into the SkPicture takes up that same 68 or 112 bytes inside the picture, with a time cost mostly in proportion to the number of attached effects, and when the SkPicture dies, we run over all the paints, unreffing all the effect pointers.

There are other viable strategies for recording SkPaints into SkPictures that could conceivably be more efficient, either using less RAM or less time or both.  E.g. SkPaint deduplication with a hash table, or variable-length encoding of the SkPaints into the SkPicture, or having SkPaint be a simple shell around a ref-counted object holding the real data.  I would be happy to nerd out in detail on these ideas, but generally, I haven't been able to make these approaches work better than the status quo yet.

One thing that's not currently feasible is to make the SkPaints themselves ref counted.  The Skia APIs are pretty strongly geared to be compatible with SkPaints on the stack, and Chrome+Blink make pretty heavy use of that.  I'd hazard an SkPaint on the stack is much more common today than an SkPaint on the heap.

So, what recommendation does all this imply?  Less malloc churn is always a good thing.  If you can cache effects sensibly, I'd do so.  If you can cache paints sensibly, I'd do so.  It's probably worth trying this idea of storing instructions to create an SkPaint then using those instructions to create the SkPaint on the stack at the last minute before calling into Skia.  If nothing else, the struct holding those instructions can probably be made smaller, scaling with only the parts of the SkPaint API you actually use.

Does Dart support stack allocation?

What about threads?  If you're guaranteed to be single threaded, our default thread-safe ref counting may be overkill.

**Comment by abarth** [comment]
> It's probably worth trying this idea of storing instructions to create an SkPaint then using
> those instructions to create the SkPaint on the stack at the last minute before calling into Skia

Ok. I'll try that approach.

> Does Dart support stack allocation?

Nope.  It's a generational, compacting GC system, which essentially means that finalizer-free, short-lived objects are very cheap because they'll just be dropped the first time the newest generation is compacted.

The trouble is that the Dart object we're using to wrap an SkPaint has a finalizer that it uses to free the C++ memory for the SkPaint.  Instead, I'm going to try what you recommend and make our Dart Paint object a pure Dart object with no finalizer and create the "real" SkPaint object on the stack immediately before calling to the SkCanvas.

> What about threads? If you're guaranteed to be single threaded, our default thread-safe ref counting may be overkill.

Pictures are recorded on a single thread and played back on a different thread.  Given that we cache some objects (e.g., gradients, color filters) on the recording thread, I think we do need thread-safe ref counting.

**Comment by eseidelGoogle** [comment]
I don't see these anymore @abarth and @vlidholt.  I suspect that the Paint/ColorFilter refactorings to create fewer wrapped objects solved this for now.

**Comment by abarth** [comment]
The pauses are much smaller now.
